version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "Asia/Tokyo"
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "Asia/Tokyo"
